### ISSUE TITLE
Please include the guide for Class Based API Views from django rest framework

### ISSUE THREAD

**Issue by whitebumblebee** [spookylukey/django-views-the-right-way#10]
I found out about this guide today. I will take my time to read it well. But skimming over the topics, I found out that you have not covered about Class Based API views from django rest framework(including ViewSets). I am relatively new, So, I might not be aware if this is alone enough for DRF also. But if there are some extra things to look for while writing class based views while writing API views, please do include it as nowadays the use of rest api's increasing day by day and Django Rest Framework is used widely while creating rest apis with django. Finally, Thank you very much for such amazing guide.

**Comment by spookylukey** [comment]
I have some comments here - https://spookylukey.github.io/django-views-the-right-way/delegation.html?highlight=drf#discussion-going-further-with-generics - perhaps that is of help?

**Comment by whitebumblebee** [comment]
Yeah I think this is good. I will go through it and will again raise the issue with more particular request if any. Thank you
